"""Fractional factorial 2^(k-p) generators, 3 to 21 factors and 4 to 512 runs.

Found by computer search: maximum resolution, then minimum aberration (as few shortest words in the defining
relation as possible). The resolution of each cell matches the standard two-level factorial table. Key (k, p);
letters = base factors A, B, C, ... (without the letter I)."""

SEARCHED_GENERATORS = {
    (3, 1): ['AB'],
    (4, 1): ['ABC'],
    (5, 1): ['ABCD'],
    (5, 2): ['ABC', 'AB'],
    (6, 1): ['ABCDE'],
    (6, 2): ['ABD', 'ABC'],
    (6, 3): ['ABC', 'AC', 'BC'],
    (7, 1): ['ABCDEF'],
    (7, 2): ['ABCD', 'CDE'],
    (7, 3): ['ABD', 'BCD', 'ABC'],
    (7, 4): ['ABC', 'AB', 'AC', 'BC'],
    (8, 1): ['ABCDEFG'],
    (8, 2): ['ABCD', 'BDEF'],
    (8, 3): ['ABCD', 'ADE', 'ABE'],
    (8, 4): ['BCD', 'ACD', 'ABC', 'ABD'],
    (9, 1): ['ABCDEFGH'],
    (9, 2): ['ABCDE', 'ABCFG'],
    (9, 3): ['ABC', 'BCEF', 'ACDF'],
    (9, 4): ['ABCDE', 'ABE', 'ACD', 'ABC'],
    (9, 5): ['ABCD', 'ABC', 'BCD', 'ACD', 'ABD'],
    (10, 1): ['ABCDEFGHJ'],
    (10, 2): ['ABCDEG', 'ACEFH'],
    (10, 3): ['ABCF', 'ACDG', 'ABEG'],
    (10, 4): ['ACF', 'ABCD', 'CDEF', 'BDE'],
    (10, 5): ['ABCDE', 'BCD', 'BDE', 'ABE', 'ABC'],
    (10, 6): ['ABCD', 'ABC', 'BCD', 'ABD', 'ACD', 'AD'],
    (11, 2): ['ABCDEFJ', 'ABCDGH'],
    (11, 3): ['ABCEF', 'ABCDH', 'ABDEG'],
    (11, 4): ['ABCDEFG', 'BDEG', 'CDEF', 'ACEG'],
    (11, 5): ['ABCDEF', 'BCDF', 'ABCE', 'ABD', 'BEF'],
    (11, 6): ['ABCDE', 'BCD', 'ABE', 'BDE', 'ABC', 'ACD'],
    (11, 7): ['ABCD', 'ACD', 'ABC', 'BCD', 'ABD', 'AB', 'BD'],
    (12, 3): ['ABDEGH', 'ABCDF', 'ACEHJ'],
    (12, 4): ['ABCFH', 'ABEGH', 'BDEFG', 'ABCDE'],
    (12, 5): ['ABCDEFG', 'BCDF', 'ABCE', 'ACDG', 'CEFG'],
    (12, 6): ['ABCDE', 'ABF', 'BCDF', 'ACF', 'ADEF', 'BCEF'],
    (12, 7): ['ABCDE', 'ACD', 'ADE', 'ABC', 'ABE', 'BCE', 'BCD'],
    (12, 8): ['ABCD', 'BCD', 'ACD', 'ABD', 'ABC', 'BD', 'CD', 'AD'],
    (13, 4): ['ABCEH', 'CDFHJ', 'ABCDFG', 'ADEGJ'],
    (13, 5): ['ACDEFGH', 'ABCDE', 'BCDFG', 'ABCFH', 'CEGH'],
    (13, 6): ['ADG', 'BCDG', 'ABFG', 'ABDE', 'ABCEF', 'CDEF'],
    (13, 7): ['ABDEF', 'ACE', 'ABCF', 'CDF', 'BCDE', 'ADE', 'CEF'],
    (13, 8): ['ABCDE', 'BDE', 'ACD', 'ABD', 'CDE', 'ACE', 'ABE', 'ADE'],
    (13, 9): ['ABCD', 'ACD', 'ABD', 'ABC', 'BCD', 'CD', 'AD', 'BD', 'AB'],
    (14, 5): ['ABDEFGH', 'ABCDEJ', 'ACDFH', 'BDFGJ', 'CDEGHJ'],
    (14, 6): ['ABCDEFGH', 'ABFGH', 'ADEFG', 'BCEFG', 'CDFH', 'ABEF'],
    (14, 7): ['ABCDEFG', 'BCFG', 'ACDG', 'ABEG', 'CEFG', 'ABCE', 'BDEF'],
    (14, 8): ['ABCDEF', 'ABDF', 'ACDE', 'DEF', 'BCD', 'ABCF', 'ACEF', 'ABDE'],
    (14, 9): ['ABCDE', 'ABC', 'CDE', 'ACD', 'BCE', 'ABD', 'BCD', 'ABE', 'BDE'],
    (14, 10): ['ABCD', 'ABD', 'BCD', 'ACD', 'ABC', 'BD', 'AD', 'CD', 'AC', 'AB'],
    (15, 6): ['ABCDEFGHJ', 'AEGHJ', 'ABCGH', 'ACDEF', 'ABFGJ', 'ABDHJ'],
    (15, 7): ['ABCFH', 'CDFG', 'ABDFG', 'AEFGH', 'ABCEGH', 'ADEG', 'BCDEF'],
    (15, 8): ['ABCDEFG', 'ACEG', 'ABFG', 'ABDE', 'ACDF', 'ADFG', 'BCDF', 'BDEG'],
    (15, 9): ['ABCDEF', 'BCEF', 'ACDE', 'DEF', 'ABE', 'ACDF', 'ABCF', 'BCDE', 'BDF'],
    (15, 10): ['ABCDE', 'CDE', 'BCE', 'ABC', 'ACD', 'BDE', 'BCD', 'ABD', 'ACE', 'ADE'],
    (15, 11): ['ABCD', 'BCD', 'ABD', 'ABC', 'ACD', 'BC', 'AC', 'CD', 'AD', 'BD', 'AB'],
    (16, 7): ['ACEFG', 'ACDEJ', 'ABCDH', 'CDEGH', 'ABFGH', 'BCGHJ', 'ABDFJ'],
    (16, 8): ['ABCDEFGH', 'ACDEH', 'BDEG', 'CEFH', 'ABFH', 'CDGH', 'ACEFG', 'ABEGH'],
    (16, 9): ['ABCDEFG', 'ABCG', 'CEFG', 'BCDF', 'ACDE', 'ABFG', 'BCEG', 'BDEF', 'ABDE'],
    (16, 10): ['ABCDEF', 'ABEF', 'CDEF', 'ACE', 'BDE', 'ADEF', 'ABCF', 'BCDF', 'ABD', 'BCE'],
    (16, 11): ['ABCDE', 'ACD', 'ABD', 'ABE', 'ACE', 'ABC', 'ADE', 'BCD', 'CDE', 'BDE', 'BCE'],
    (17, 8): ['ABCEF', 'ACDGJ', 'DEGHJ', 'ACEFGHJ', 'BCDFJ', 'ABEGJ', 'ADFGH', 'ABCDEHJ'],
    (17, 9): ['BCGH', 'BDEFGH', 'ABDE', 'ABCFH', 'AEFH', 'BCDEG', 'BCDF', 'ACDFG', 'ABEGH'],
    (17, 10): ['ABCDEFG', 'DEFG', 'ABDF', 'ACDG', 'BCDE', 'CDEF', 'BCEG', 'ACFG', 'ABCF', 'ABDG'],
    (17, 11): ['ABCDEF', 'ABCF', 'ABDE', 'ACD', 'AEF', 'ABDF', 'BCEF', 'BCDE', 'DEF', 'CDF', 'ACE'],
    (17, 12): ['ABCDE', 'ABC', 'ADE', 'ABD', 'ACE', 'CDE', 'BCD', 'ABE', 'BCE', 'BDE', 'ACD', 'ABCE'],
    (18, 9): ['ABCDEFGHJ', 'CDEFJ', 'BEFHJ', 'ACFGH', 'ABDEF', 'ABCEH', 'BDGHJ', 'ABFGJ', 'BCDFG'],
    (18, 10): ['DEFH', 'ABCDEFH', 'ABEFG', 'ABCDG', 'BGH', 'ABDF', 'ADEGH', 'BCDEG', 'CDFGH', 'BCEF'],
    (18, 11): ['ABCDEFG', 'BDEG', 'ABEF', 'ACEG', 'CDEF', 'BEFG', 'BCDE', 'ADEG', 'ADEF', 'ABCE', 'CEFG'],
    (18, 12): ['ABCDE', 'BCDEF', 'ABCEF', 'ABCDF', 'ABDEF', 'ACDEF', 'AEF', 'ACD', 'BDE', 'ADE', 'CDF', 'ABC'],
    (18, 13): ['ABCDE', 'ABD', 'ACD', 'BDE', 'CDE', 'BCE', 'ADE', 'BCD', 'ABE', 'ACE', 'ABC', 'BCDE', 'ABCD'],
    (19, 10): ['ABCDEFGH', 'ABFHJ', 'ACEGHJ', 'BDGHJ', 'DEFH', 'ADEFJ', 'ABCDF', 'BDEG', 'CFGJ', 'ADGH'],
    (19, 11): ['ABCDEFGH', 'AEFGH', 'BDEFH', 'CDFG', 'ABCGH', 'ABEG', 'BDFG', 'ABCFH', 'BCDE', 'CDEGH', 'ACEF'],
    (19, 12): ['ABCDEFG', 'CDEF', 'ACFG', 'ABCD', 'BCEG', 'DEFG', 'BCDG', 'ABDE', 'ADFG', 'ABEG', 'ACEF', 'ACDEG'],
    (19, 13): ['BCE', 'ABDEF', 'ACE', 'ABD', 'DEF', 'BEF', 'ACF', 'BCD', 'ADF', 'CDE', 'ABE', 'ACDEF', 'CEF'],
    (19, 14): ['ABCDE', 'BDE', 'CDE', 'ABD', 'ACD', 'BCE', 'ADE', 'ABE', 'ABC', 'ACE', 'BCD', 'ABCD', 'ABDE', 'ACDE'],
    (20, 11): ['CFGH', 'ABDEH', 'ADEFG', 'BDFJ', 'ABCDG', 'ACHJ', 'BCDEFH', 'BCEGJ', 'ACDEFJ', 'ABFGHJ', 'EGHJ'],
    (20, 12): ['ABCDEFGH', 'BDEGH', 'BCGH', 'CDEFH', 'ABCE', 'DEFG', 'ACFGH', 'BCDFH', 'ABEFH', 'BCEF', 'ACDF', 'ABEFG'],
    (20, 13): ['ABCDEFG', 'ABCD', 'BDFG', 'BCEF', 'ABEG', 'ACDE', 'AEFG', 'ABCF', 'CDEF', 'BDEG', 'ADFG', 'ABDEF', 'DEFG'],
    (20, 14): ['ABDEF', 'AEF', 'ABD', 'ACE', 'CDF', 'DEF', 'ABF', 'ACF', 'ADE', 'BCD', 'BCE', 'BCF', 'BDE', 'ABC'],
    (20, 15): ['ABCDE', 'ACD', 'BCE', 'ABC', 'CDE', 'ADE', 'BDE', 'ACE', 'ABE', 'ABD', 'BCD', 'ABCD', 'BCDE', 'ABDE', 'ACDE'],
    (21, 12): ['ABCDEFGHJ', 'ACEG', 'ABEFH', 'ABCFJ', 'ACDFH', 'DEFGJ', 'BCDEGH', 'ABDEJ', 'BCGHJ', 'BCEJ', 'BCEFG', 'BDFGH'],
    (21, 13): ['ABCDEFGH', 'ACDEF', 'CEFGH', 'ABCEG', 'ABDFGH', 'ABCF', 'BCDEG', 'ACDEH', 'BCEFH', 'CDFG', 'BCDH', 'ABCDG', 'ACGH'],
    (21, 14): ['ABCDEFG', 'ABDE', 'ABCG', 'AEFG', 'ACDF', 'BDEG', 'ABEF', 'BCFG', 'ACDG', 'BCDF', 'DEFG', 'ABDFG', 'ADEG', 'ABCF'],
    (21, 15): ['ABC', 'ACF', 'ABF', 'DEF', 'BCE', 'ACD', 'BDF', 'CDE', 'ABE', 'BCF', 'AEF', 'ABDEF', 'BCD', 'ADE', 'CDF'],
    (21, 16): ['ABCDE', 'ACD', 'BCD', 'BDE', 'ADE', 'ABE', 'ABD', 'ACE', 'CDE', 'ABC', 'BCE', 'ABCE', 'ABCD', 'ABDE', 'ACDE', 'BCDE'],
}
